version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://todo-list-pruebas

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
