version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g yarn
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
